# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    jira_calculator:
        class: AppBundle\Utils\JiraCalculator
        arguments: ['@jira_api.issue', '@jira_api.search']
