parameters:
    #parameter_name: value

services:
    jira_calculator:
        class: AppBundle\Utils\JiraCalculator
        arguments: ['@jira_api.issue', '@jira_api.search']

    trello_api:
        class: AppBundle\Utils\TrelloApiService