parameters:
    #parameter_name: value

services:
    jira_calculator:
        class: AppBundle\Utils\JiraCalculator
        arguments: ['@jira_api.issue', '@jira_api.search', @doctrine.orm.entity_manager]

    trello_api:
        class: AppBundle\Utils\TrelloApiService
        arguments: [@service_container]

    issue_form:
        class: AppBundle\Form\IssueType
        tags:
            - { name: form.type }

    confluence_api:
        class: AppBundle\Utils\ConfluenceApiService
        arguments: [@service_container]

    graph_creator:
      class: AppBundle\Utils\GraphCreator
      arguments: []